name = "lean-bdiff"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanBdiff"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = false
linter.unusedSimpArgs = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0-rc6"

[[lean_lib]]
name = "LeanBdiff"

[[lean_lib]]
name = "Ffi"

[[lean_exe]]
name = "test-vcdiff"
root = "Test.VcdiffTest"

[[lean_exe]]
name = "bench-vcdiff"
root = "Test.Bench"
